services:
  - type: web
    name: void-ai-website-builder
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: AUTH_SECRET
        generateValue: true
      - key: HF_API_TOKEN
        sync: false
      - key: NVIDIA_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.3-70b-versatile
      - key: VERCEL_TOKEN
        sync: false
      - key: VERCEL_TEAM_ID
        sync: false
      - key: BLOB_READ_WRITE_TOKEN
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_OWNER
        sync: false
      - key: FIREBASE_PROJECT_ID
        value: voide-817de
      - key: FIREBASE_API_KEY
        value: AIzaSyBWRRPrgJhrFtXifgrvIU2qeleXaIEwrsw
      - key: FIREBASE_AUTH_DOMAIN
        value: voide-817de.firebaseapp.com
      - key: FIREBASE_APP_ID
        value: "1:114144022124:web:dfbd64b642f5b8b3bbd249"
      - key: FIREBASE_MESSAGING_SENDER_ID
        value: "114144022124"
    healthCheckPath: /
    autoDeploy: true
